In [10]:
import numpy as np

a = np.array([1,2,3])
print(a)
print(type(a))

b = np.array((1,2,3))
print(b)
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


In [12]:
b[2] = 10
print(b)

[ 1  2 10]


In [17]:
c = np.array([[1,2,3],[2,3,4]])
print(c)

d = np.array([(1,2,3),(2,3,4)])
print(d)

e = np.array(((1,2,3),(2,3,4)))
print(e)

[[1 2 3]
 [2 3 4]]
[[1 2 3]
 [2 3 4]]
[[1 2 3]
 [2 3 4]]


In [18]:
f = np.array([[1,2,3],[2,3,4],[3,4,5]])
print(f)

[[1 2 3]
 [2 3 4]
 [3 4 5]]


In [3]:
import numpy as np
a = np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
import numpy as np
a = np.array([10,25,45])
a

array([10, 25, 45])

In [14]:
import numpy as np
a = np.arange(10,25,5)
print(a)

[10 15 20]


In [17]:
import numpy as np
a = np.arange(100,5,-15)
print(a)

[100  85  70  55  40  25  10]


In [22]:
import numpy as np
a = np.linspace(42,45,10)
print(a)

[42.         42.33333333 42.66666667 43.         43.33333333 43.66666667
 44.         44.33333333 44.66666667 45.        ]


In [24]:
import numpy as np
a = np.full((4,4),2)
print(a)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [26]:
import numpy as np
a = np.full((4,4),9)
print(a)

[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


In [36]:
import numpy as np
a = np.random.random((3,4))
print(a)

[[0.90778483 0.71565923 0.93831806 0.3335979 ]
 [0.69268713 0.49397423 0.44710765 0.91400773]
 [0.3231422  0.98209772 0.74831705 0.54139976]]


In [41]:
import numpy as np
a = np.array([[2,3,4],[3,4,5]])
print(a)
a.shape

[[2 3 4]
 [3 4 5]]


(2, 3)

In [43]:
a.shape = (3,2)
print(a)

[[2 3]
 [4 3]
 [4 5]]


In [48]:
print(a.shape[0])
print(a.shape[1])

3
2


In [50]:
a.shape = (6,1)
print(a)

[[2]
 [3]
 [4]
 [3]
 [4]
 [5]]


In [51]:
import numpy as np
a = np.arange(24)
print(a)
a.size

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


24

In [52]:
n = int(input("Enter the Elements in a List : "))
import numpy as np
a = np.arange(n)
print(a)
a.size

Enter the Elements in a List : 5
[0 1 2 3 4]


5

In [56]:
import numpy as np
n = int(input("Enter the Elements in a List : "))
a = np.arange(n)
print(a.dtype)
print(a.ndim)
b = a.reshape(2,4,3)
print(b.ndim)

Enter the Elements in a List : 24
int32
1
3


In [59]:
import numpy as np
a = np.linspace(5,7,24)
print(a)
print()
print(a.dtype)

[5.         5.08695652 5.17391304 5.26086957 5.34782609 5.43478261
 5.52173913 5.60869565 5.69565217 5.7826087  5.86956522 5.95652174
 6.04347826 6.13043478 6.2173913  6.30434783 6.39130435 6.47826087
 6.56521739 6.65217391 6.73913043 6.82608696 6.91304348 7.        ]

float64
